### ISSUE TITLE
Porušenie prístupnosti bod 2.4.4 pri tlačidlách Viac informácií

### ISSUE THREAD

**Issue by athelas64** [slovensko-help/korona-gov#100]
V rámci stránky https://wpkorona.lamer.sk/prva-a-druha-pomoc/ tlačidlá/odkazy Viac informácií porušujú pravidlo [2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context)  (pri tabovaní s čítačom po stránke používateľ počuje za sebou len Viac informácií Viac informácií Viac informácií.

Ak nechceme celú stránku sémanticky  prekopať, t.j. spraviť tlačidlom samotný nadpis a zrušiť komponenty Viac informácií (ono tam totiž zas nie je až tak veľa tých informácií, šlo by to vyriešiť cez aria-label. Napr. `aria-label="Viac informácií o odklade platieb a odvodov"`. Ak by čítač (napr. NVDA) nebral aria-label, bude treba textu priradiť aj `role="heading" aria-level="3"`. Čítače štandardne aria-label na statických prvkoch ignorujú.

Pri uvedenom spôsobe bude nevidiaci počuť "_Viac informácií o odklade platieb a odvodov._" ~~Viac informácií tlačidlo zatvorené. Síce sa tam opakujú slová a nie je to ideálne, ale je to oveľa lepšie ako teraz.~~

**Comment by Peter74** [comment]
PR - #102

- [ ] Bude treba po nasadení vyplniť popisné pole - ktoré bolo pridané a výsledok otestovať v čítačkách

**Comment by athelas64** [comment]
`<span class="govuk-details__summary-text" aria-label="o rokovaní Ministerstva financií SR s bankami" role="heading" aria-level="3">Viac informácií</span>`

Toto som otestoval a funguje to dobre s čítačom.

**Comment by Peter74** [comment]
role a aria-label sú v PR #105
