### ISSUE TITLE
Odkazy viac informácií o aplikácii

### ISSUE THREAD

**Issue by athelas64** [slovensko-help/korona-gov#120]
Odkazy na homepage v časti užitočné aplikácie nie sú sémanticky v poriadku a je potrebné k nim doplniť prvok title, ktorý skonkretizuje, viac informácií o akej aplikácii a 
- zrušiť otváranie odkazu v novom okne, alebo
- doplniť informáciu, že dôjde k otvoreniu nového okna do textu v textovej podobe a doterajšou ikonkou, alebo
-  doplniť túto informáciu minimálne do title

Príklad:
<a ~~target="_blank"~~ class="govuk-link " **title="Viac informácií o aplikácii Zostaň zdravý _- nové okno_"** href="https://old.korona.gov.sk/COVID19-ZostanZdravy.php">Viac o aplikácii</a>

**Comment by Peter74** [comment]
Upravené. nechal som otváranie na novej karte a doplnil som title aj s info o novom okne a info, ako je Príklad.
To isté som spravil aj pre EN a HU verziu - hlavne tú HU verziu by mohol potom niekto skontrolovať, texty som iba v Google translatore preložil (momentálne je HU verzia ešte nepreložená).
