### ISSUE TITLE
Button so svg ikonou "start" MUSI mat class govuk-button--start

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#126]
Bez tej classy to robi taketo psie kusy:

<img width="265" alt="Screenshot 2020-04-20 at 11 10 08" src="https://user-images.githubusercontent.com/1244233/79734763-85b53600-82f7-11ea-9d46-3e1d3baba0d8.png">

**Comment by Peter74** [comment]
done
