### ISSUE TITLE
XML sitemapy je nevalidne

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#130]

**Comment by Peter74** [comment]
...neviem, čo presne je zlé, ale

- tu je komplet sitemapa: https://wpkorona.lamer.sk/sitemap_index.xml

- tu sú všetky stránky, principiálne nám táto stačí: https://wpkorona.lamer.sk/page-sitemap.xml

**Comment by Peter74** [comment]
<img width="587" alt="Screenshot 2020-04-20 at 15 33 18" src="https://user-images.githubusercontent.com/6866481/79757369-4cdb8800-831c-11ea-8c9c-5baca11cba9d.png">
<img width="1085" alt="Screenshot 2020-04-20 at 15 33 33" src="https://user-images.githubusercontent.com/6866481/79757401-5533c300-831c-11ea-8897-f13d51c6b875.png">

**Comment by filiplikavcan** [comment]
Jedna sa o sitemapu v statickom exporte, ktora je z nejakeho dovodu nevalidna: https://www.korona.gov.sk/sitemap_index.xml

**Comment by Hucoo** [comment]
Zajtra to pozriem, možno to bude chyba wp static

**Comment by filiplikavcan** [comment]
Podarilo sa ti nieco zistit?

**Comment by Hucoo** [comment]
Áno podarilo. Bude tam zrejme potrebné generovať ju "manuálne" alebo iným spôsobom, nie nechať to na plugin. Lebo v zdrojovom kóde sa neskôr dotazuje na ďalšiu URL, ktorá tam ale nie je / nefunguje lebo to je statika.

<img width="1440" alt="Snímka obrazovky 2020-04-21 o 10 01 38" src="https://user-images.githubusercontent.com/25851535/80405102-710e0a80-88c2-11ea-8d1f-6a3c24df5ac9.png">
<img width="904" alt="Snímka obrazovky 2020-04-21 o 10 05 17" src="https://user-images.githubusercontent.com/25851535/80405115-7408fb00-88c2-11ea-8f3e-23711bb2288d.png">

**Comment by filiplikavcan** [comment]
OK, fixneme to pri deployi tak, ze v tych XMLkach odstranime toto:  `<?xml-stylesheet type="text/xsl" href="//korona.gov.sk/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>`.

**Comment by b0n0r** [comment]
will get fixed once the domain is set (ref. #145)

**Comment by b0n0r** [comment]
sitemap is valid, since the domain is now correctly set to 'korona.gov.sk'
https://korona.gov.sk/sitemap_index.xml
