### ISSUE TITLE
Texty na homepage

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#138]
![image](https://user-images.githubusercontent.com/26342/79757463-6aa8ed00-831c-11ea-9fed-d5f40405ba4a.png)

Vynechal by som to "Tu nájdete", dal tvrdu medzeru za predlozky jednopismenove (aby to nezalamovalo) a cele zabalil do `govuk-body-lead`.

**Comment by Peter74** [comment]
- class je doplnený

**Comment by ljurena** [comment]
upravené
