### ISSUE TITLE
Príznaky ochorenia obsahujú aj iné údaje

### ISSUE THREAD

**Issue by jojurko** [slovensko-help/korona-gov#143]
https://www.old.korona.gov.sk/covid-19-patient-form.php
v casti: Ktoré príznaky ochorenia máte? sú možnosti ako:
Prišiel som zo zahraničia 
Fajčiar 
Očkovaný proti chrípke

**Comment by filiplikavcan** [comment]
Tento formular je este sucastou povodneho webu a bude v najblizsich dnoch prerobeny.
