### ISSUE TITLE
Jednotna verzia URL - s www alebo bez www

### ISSUE THREAD

**Issue by RUjmiak** [slovensko-help/korona-gov#145]
Vsetky linky na webe smeruju na https://korona.gov.sk a nasledne su redirectnute na https://www.korona.gov.sk  - google toto nema rad pretoze medzi kazdym requestom je 302 redirect, nie len ze to je zle z pohladu SEO ale zbytocne to spomaluje web.

Je potrebne vybrat jednu verziu a vsetky URL by mali byt podla toho upravene.

**Comment by b0n0r** [comment]
treba sa rozhodnut co ma byt cielovy stav, nasledne mozme fixnut absolutne cesty v kode a presmerovania samotne

**Comment by b0n0r** [comment]
zhodli sme sa ze base URL bude *bez* www teda "korona.gov.sk"

**Comment by b0n0r** [comment]
po nastaveni redirectov na strane F5 je hlavna domena v non-www formate 'korona.gov.sk'
