### ISSUE TITLE
Improve leading home page text

### ISSUE THREAD

**Issue by andrewshadura** [slovensko-help/korona-gov#146]
> How to prevent infection?
> 
> * Stay home if possible. Leave your house or apartment only in necessary cases.
> * Wearing a face mask whenever you leave your house or apartment helps to protect yourself and others.
> * Keep at least 2 meters away from other people if you must go outside.
> * Wash your hands immediately after returning to your home. 
> 
> Limit meetings with friends and family members outside of your household  to minimum. You can spread the disease without showing any symptoms.

This probably would be slightly better (why not reuse some text from [gov.uk](https://www.gov.uk/coronavirus)?):

> How to protect yourself and others
> 
> * Stay at home if you can. You should only leave the house for very limited purposes.
> * If you go out, wear a face mask to reduce the spread of infection.
> * Stay 2 metres away from other people at all times.
> * Wash your hands as soon as you get home.
> 
>  Do not meet others, even friends or family, unless you live in the same household. You can spread the virus even if you don’t have symptoms.

**Comment by andrewshadura** [comment]
6 days, no action :disappointed:

**Comment by martin835** [comment]
done
