### ISSUE TITLE
Rozkliknuté taby by mohli zmeniť url s dodatkom kotvy pre jednoduché zdieľanie

### ISSUE THREAD

**Issue by orflex** [slovensko-help/korona-gov#147]
Posielam presne, čo myslím. 
**https://www.beyou.sk/caste-otazky/#starostlivost-o-bizuteriu**

Ide o to, že teraz sa url nemení a musím slovne nanavigovať človeka, kde to nájde. 
Z

**Comment by frkosk** [comment]
Rozumiem čo myslíš, GOVUK a ID-SK pattern je taký, že pri kliku sa ti predošlí accordion nezbalí. 
V tom prípade by bolo čudné aby sa ti menila URL.
Ak sa chceme odkazovať piamo na nejaký accordion, tak môžeme. Po príchode na stránku bude mať focus. Takto http://idsk-preview.herokuapp.com/components/accordion/preview#default-example-heading-1

To čo vravíš máme pri taboch.
