### ISSUE TITLE
Zobrazovať "Kĺzavý medián denných prírastkov za ostatných sedem dní"

### ISSUE THREAD

**Issue by Xubor** [slovensko-help/korona-gov#152]
Podľa vyhlásenia premiéra, prechod medzi "fázami obmedzení" sa má riadiť najmä hodnotou _kĺzavého mediánu denných prírastkov (počtu zistených nakazených) za ostatných sedem dní_.
Tento parameter je preto mimoriadne dôležité sledovať, a bude to zaujímať množstvo ľudí. 

**Toto je vlastne najdôležitejšie číslo** - závisí od neho oveľa viac ako od počtov vzoriek, alebo sumy nakazených od začiatku diagnostiky. Na tomto webe by mali byť zobrazené údaje, od ktorých aj niečo závisí, nielen štatistické číselká, ktoré si aj tak viem v lepšom kontexte a grafike nájsť inde. (Toľko k motivácii. ;-) )

Mal by sa teda zobrazovať na stránke, najlepšie v časti Koronavírus v číslach.

**Comment by b0n0r** [comment]
ready to be closed? @filiplikavcan

**Comment by filiplikavcan** [comment]
@b0n0r zatvaraj podla svojho svedomia a vedomia

**Comment by Xubor** [comment]
Ďakujem za pekné spracovanie tejto témy.
