### ISSUE TITLE
Pokazena titulka statistikami.

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#154]
Cisla uplne hore na titulke su velmi zvlastne riesenie. 

- neviem aky problem to riesi. Preco su tieto cisla dolezite? Ved podla nich sa nic neriadi. (To podla ktoreho sa budu uvolnovat opatrenia tam nie je) IMHO Ovela dolezitejsie su pre beznych ludi opatrenia, co maju robit, kde najdu pomoc, ako sa otestovat.

- su tam dve aktualizacie pod sebou, je to velmi divne. 

![image](https://user-images.githubusercontent.com/26342/79953849-cee2c280-847c-11ea-8f86-4c145423a402.png)

- na mobile to uplne rozbija stranku (nevidim ani nadpis, ani kde som ani nic)

![image](https://user-images.githubusercontent.com/26342/79954035-0b162300-847d-11ea-9d34-d9a9fedb7a8b.png)

- na vzorovej (https://www.gov.uk/coronavirus) z ktorej vychadzame, su cisla az niekde dole v podsekcii. ked uz nic ine, mohli by sme to dat pod to najdolezitejsie?

Napriklad takto. 

![image](https://user-images.githubusercontent.com/26342/79954239-56c8cc80-847d-11ea-88c8-82d82b6d18eb.png)

**Comment by frkosk** [comment]
Spravíme verziu 2.0 to ako to má kanada sa mi tiež páči.
