### ISSUE TITLE
Odstrániť divné znaky

### ISSUE THREAD

**Issue by frkosk** [slovensko-help/korona-gov#17]
na stránke https://wpkorona.lamer.sk/prva-a-druha-pomoc/prispevok-pre-szco-pri-poklese-trzieb/
v druhom akordeone je pred každým paragrafom dvojica znakov. Nevidím ich v souce :-/

![wpkorona lamer sk_prva-a-druha-pomoc_prispevok-pre-szco-pri-poklese-trzieb_](https://user-images.githubusercontent.com/2466674/78778783-1e64c100-799c-11ea-8ad3-05b8b68bffef.png)

**Comment by filiplikavcan** [comment]
Opravil som to.
