### ISSUE TITLE
55 dni a stale ziadne zlepsienie 

### ISSUE THREAD

**Issue by michalfin** [slovensko-help/korona-gov#199]
Ahoj Ako som uz pisal v emaili 2 mesiace dozadu. 

![image](https://user-images.githubusercontent.com/67193101/122802849-2ae5e880-d2c6-11eb-9287-c1ce0f8fe3c4.png)

-> dat info ze akceptujete iba XY dni - nech to clovek nevyplna a vie ze ho to caka o 3 rano niekde na letisku :) 

https://github.com/slovensko-help/korona-gov/blob/3db92548083f6b5379b0062702d14df389453b8d/wp-content/themes/korona/ehranica-v4.php#L157

-> napisat to aspon cervenym  
https://github.com/slovensko-help/korona-gov/blob/3db92548083f6b5379b0062702d14df389453b8d/wp-content/themes/korona/ehranica-v4.php#L836

**Comment by athelas64** [comment]
hej, táto info musí byť k dispozícii na začiatku formulára a mala by byť dosť nepriehladnuteľná

**Comment by michalfin** [comment]
@athelas64 V texte mailu sa pisalo ze vyber datumu by mal prvy krok cez ktory to cloveka dalej nepusti. Ale ukratilo by to cloveka o tu zabavu vyklikavat si 6 krajin. Je smutne ze ako malo chyba k lepsiemu rieseniu a ako dlho to trva...

Aby to neznelo ze len kecam co tu nefunguje, ja som sa ponukol ze im to spravim (zadarmo) len staci povedat, mail bol bez odpovede.

**Comment by michalfin** [comment]
Zatvaram s https://www.aktuality.sk/clanok/905342/koronavirus-do-ehranice-je-mozne-zaregistrovat-sa-30-dni-pred-prichodom-na-slovensko/

Dakujem za ochotu a za snahu zlepsit sluzby obcanom!
