### ISSUE TITLE
"Ak bolo pridelene" nema byt v zatvorke za ICO?

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#20]
Vo figme je: "Do predmetu emailu uveďte: “Opatrenie č.1 – názov žiadateľa (názov firmy alebo SZČO) – IČO”, ak bolo pridelené."

Nema to byt takto? "Do predmetu emailu uveďte: “Opatrenie č.1 – názov žiadateľa (názov firmy alebo SZČO) – IČO (ak bolo pridelené)"

**Comment by frkosk** [comment]
Je to tam
