### ISSUE TITLE
Divný znak na na konci riadku

### ISSUE THREAD

**Issue by frkosk** [slovensko-help/korona-gov#23]
https://wpkorona.lamer.sk/prva-a-druha-pomoc/?preview_id=26&preview_nonce=49421ed22e&preview=true#podnikatel
![image (4)](https://user-images.githubusercontent.com/2466674/78800063-4c0d3280-79bb-11ea-98a9-a3cc310f1b36.png)

**Comment by filiplikavcan** [comment]
Este to tam vidis? Ja to v Chrome/Mac uz nevidim. Ak to este vidis, tak v akom prehliadaci?

**Comment by frkosk** [comment]
Screenshot je z win (prehliadač neviem). Mne na macu sa zobrazujú podobné znaky. Zaujímavé je, že niektoré vidia oba systémy niektoré iba jeden.
Skúšal som odstraňovať tie, ktoré som videl v editácii stranky. Ale šli len tie na konci riadku. Ak boli niekde v texte nešlo ich zmazať. Neviem čo s tým.

**Comment by filiplikavcan** [comment]
Zaujimave, ja to vidim bez znakov.

**Comment by b0n0r** [comment]
bol to zvlastny utf8 znak https://www.fileformat.info/info/unicode/char/2028/index.htm
prejavovalo sa to vo FF @ windows10, fixnute v raw HTML
zrejme chyba pri copy-paste z figmy?
