### ISSUE TITLE
Pridať pre SZCO bez zamest. 2B nove cestne prehlasenie

### ISSUE THREAD

**Issue by ljurena** [slovensko-help/korona-gov#31]
Namiesto sucasneho cestneho prehlasenia pridat toto nove: 

1) som nebol k 31.12.2019 podnikom v ťažkostiach
--
2)    v súvislosti s vyhlásením   mimoriadnej situácie, núdzového stavu alebo výnimočného stavu mi poklesli   tržby,
3)    spĺňam podmienky v zmysle § 70 ods. 7   zákona o službách zamestnanosti, a to tým, že:
a) mám splnené daňové povinnosti   podľa zákona č. 595/2003 Z. z. o dani z príjmov v znení   neskorších predpisov (k 29.2.2020),
b) mám splnené povinnosti odvodu   preddavku na poistné na verejné zdravotné poistenie, poistného na sociálne   poistenie a povinných príspevkov na starobné dôchodkové sporenie (k   29.2.2020),
c) neporušil som zákaz nelegálneho   zamestnávania v období dvoch rokov pred podaním žiadosti o príspevok,
d) nemám voči úradu   splatné finančné záväzky (k 29.2.2020),
e) nie som v   konkurze, likvidácii, nútenej správe alebo nemám určený splátkový kalendár   podľa zákona č. 7/2005 Z. z. o konkurze a reštrukturalizácii   a o zmene a doplnení niektorých zákonov v znení   neskorších predpisov,
f) nemám evidované neuspokojené nároky   svojich zamestnancov vyplývajúce z pracovného pomeru,
g) nemám   právoplatne uložený trest zákazu prijímať dotácie alebo subvencie alebo trest   zákazu prijímať pomoc a podporu poskytovanú z fondov Európskej únie, ak ide o   právnickú osobu,
4) nie   je voči mne nárokované vrátenie pomoci na základe predchádzajúceho   rozhodnutia Komisie, ktorým bola poskytnutá pomoc označená za nezákonnú a   nezlučiteľnú s vnútorným trhom,
5) som subjekt, ktorý vznikol a začal prevádzkovať   svoju činnosť najneskôr k 01.02.2020.

**Comment by frkosk** [comment]
hotovo
