### ISSUE TITLE
Chyba hlavičky

### ISSUE THREAD

**Issue by frkosk** [slovensko-help/korona-gov#32]
Nefunguje rozklik menu na mobile a vypúšťame názov stránky
Toto je jeho nová podoba:
![menu](https://user-images.githubusercontent.com/2466674/78810734-09525700-79c9-11ea-9343-89605d083be7.png)

**Comment by filiplikavcan** [comment]
Hotovo.

Je to bug v id-sk. Konkrente pri inicializacii hlavicky ocakava atribut data-module="govuk-header" a pri toggle pridavat govuk-*-open classy na button a navigaciu, ktore su v id-sk nahradene idsk-*-open classami. Dirty fix spociva v tom, ze som zmenil hodnotu data-module a pridal prislusne css classy do csska WP temy.

Inicializacia hlavicky je tu: https://github.com/id-sk/id-sk-frontend/blob/new_idsk/src/govuk/all.js#L50

**Comment by frkosk** [comment]
fixol som velkost loga aby licovalo s menu. je tam PR
