### ISSUE TITLE
Pridat pre pre zamestnavatelov v streame 1 cestne vyhlasenie

### ISSUE THREAD

**Issue by ljurena** [slovensko-help/korona-gov#35]
Znenie nového cestneho vyhlasenia : 

1) vyplácam svojim zamestnancom náhradu mzdy vo výške 80 %   priemerného zárobku zamestnanca podľa výkazu pre priznanie príspevku (za   marec min. 80 %, resp. podľa § 142 Zákonníka práce – nárok podľa kolektívnej   zmluvy)
--
2)   nežiadam príspevok na zamestnancov, ktorí sú vo výpovednej lehote alebo   poberajú z dôvodu prekážok v práci na strane zamestnanca dávku sociálneho   zabezpečenia,
3)   nežiadam príspevok na zamestnancov, na ktorých mi je poskytovaný iný   príspevok na mzdy/CCP (celková cena práce) v rámci AOTP (akívne opatrenia na trhu práce) z úradu práce, sociálnych vecí   a rodiny,
4)   nežiadam príspevok na zamestnancov prijatých po 01.03.2020,
5)   dva mesiace nasledujúce po mesiaci, za ktorý je príspevok poskytovaný,   neukončím pracovný pomer so zamestnancom/zamestnancami výpoveďou alebo   dohodou z dôvodov uvedených v § 63 ods. 1 písm. a) a b) zákona   č. 311/2001 Z. z. Zákonník práce,
6) som nebol k 31.12.2019 podnikom v ťažkostiach
7) spĺňam podmienky v zmysle § 70 ods. 7 zákona o službách   zamestnanosti, a to tým, že:
a) mám splnené   daňové povinnosti podľa zákona č. 595/2003 Z. z. o dani z príjmov   v znení neskorších predpisov,
b) mám splnené povinnosti odvodu   preddavku na poistné na verejné zdravotné poistenie, poistného na sociálne   poistenie a povinných príspevkov na starobné dôchodkové sporenie,
c) neporušil som zákaz   nelegálneho zamestnávania v období dvoch rokov pred podaním žiadosti o   príspevok,
d) nemám voči úradu   splatné finančné záväzky,
e) nie som v   konkurze, likvidácii, nútenej správe alebo nemám určený splátkový kalendár   podľa zákona č. 7/2005 Z. z. o konkurze a reštrukturalizácii   a o zmene a doplnení niektorých zákonov v znení   neskorších predpisov,
f) nemám   evidované neuspokojené nároky svojich zamestnancov vyplývajúce z pracovného   pomeru,
g) nemám právoplatne uložený   trest zákazu prijímať dotácie alebo subvencie alebo trest zákazu prijímať   pomoc a podporu poskytovanú z fondov Európskej únie, ak ide o právnickú   osobu,
8) nie je voči mne nárokované vrátenie pomoci na základe   predchádzajúceho rozhodnutia Komisie, ktorým bola poskytnutá pomoc označená   za nezákonnú a nezlučiteľnú s vnútorným trhom,
9)   som subjekt, ktorý vznikol a začal prevádzkovať svoju činnosť najneskôr   k 01.02.2020.

**Comment by frkosk** [comment]
na linku https://wpkorona.lamer.sk/prva-a-druha-pomoc/prispevok-zamestnavatelom-na-mzdy-zamestnancov/?preview_id=35&preview_nonce=27ccfdc273&preview=true

**Comment by frkosk** [comment]
Hotovo
