### ISSUE TITLE
Aktualizovať obrázky

### ISSUE THREAD

**Issue by frkosk** [slovensko-help/korona-gov#39]
tu https://wpkorona.lamer.sk/prva-a-druha-pomoc/zamestnavatel-podklady-pre-ziskanie-prispevku/
aj tu https://wpkorona.lamer.sk/prva-a-druha-pomoc/dokumenty-pre-ziskanie-prispevku-szco-bez-zamestnancov/

Nové sú vo figme

**Comment by frkosk** [comment]
#37

**Comment by b0n0r** [comment]
z callu: obrazky z figmy exportovat aj 2x (responzivne)
