### ISSUE TITLE
Feedbackform

### ISSUE THREAD

**Issue by ljurena** [slovensko-help/korona-gov#40]
vytvorit jendoduchy feedback form, ktorý bude ponukat nechat spatnu vazbu po prevedení uzivatela jeho user flowom. (Feedback form ako je v IDSK alebo jednoduchy google form..)

**Comment by filiplikavcan** [comment]
V navody.digital mame takyto komponent, ktory viem prehodit do id-sk, aby by bol zaujem. Doriesit by bolo potrebne to, kde sa budu data z formularov odosielat.

<img width="1126" alt="Screenshot 2020-04-08 at 20 50 45" src="https://user-images.githubusercontent.com/1244233/78822017-a9fd4280-79da-11ea-8fda-deed7a815af3.png">

<img width="1122" alt="Screenshot 2020-04-08 at 20 51 47" src="https://user-images.githubusercontent.com/1244233/78822172-e892fd00-79da-11ea-98a9-61bc05a3a8cb.png">

<img width="1123" alt="Screenshot 2020-04-08 at 20 51 55" src="https://user-images.githubusercontent.com/1244233/78822179-ec268400-79da-11ea-884d-306eaa12604d.png">
