### ISSUE TITLE
Som SZCO bez zamestnancov a v navode k ziadosti sa spominaju zamestnanci

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#43]
"Nepodpísanú žiadosť a výkaz zašlite Úradu práce, sociálnych vecí a rodiny v územnom obvode, kde sa pracovné miesta udržiavajú."

https://wpkorona.lamer.sk/prva-a-druha-pomoc/navod-ako-podat-ziadost-o-prispevok-2b/

**Comment by ljurena** [comment]
Vdaka, vyriesene, opravene.
