### ISSUE TITLE
Rodovo neutralny jazyk v tlacidlach

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#45]
<img width="695" alt="Screenshot 2020-04-08 at 22 43 07" src="https://user-images.githubusercontent.com/1244233/78833252-d9b54600-79ec-11ea-92a1-f30a493abda2.png">

Nebude toto lepsie dat v plurale? "Ano, boli sme nuteni zatvorit", atd.

**Comment by ljurena** [comment]
Tlačidla vyriešené, bol pridaný ženský rod. V plurále by to znelo divne.
