### ISSUE TITLE
Je mozne zlucit dve stranky ziadosti do jednej?

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#6]
Podla vsetkeho sa lisia len v jednom texte:

"Do predmetu emailu uveďte: “Opatrenie č.1 – názov žiadateľa (názov firmy alebo SZČO) – IČO”, ak bolo pridelené."

vs.

"Do predmetu emailu uveďte: “Opatrenie č.2 – názov žiadateľa (názov firmy alebo SZČO) – IČO”, ak bolo pridelené."

**Comment by ljurena** [comment]
Nie je to možné, pretože sa jedná o 2 rozdiel žiadosti, oaptrenie č.1 má vlastn´ý formulár a opatrenie č.2 má vlastný formulár. Alebo prosím o dovysvetlenie ako si to myslel.

**Comment by filiplikavcan** [comment]
Myslim tieto dve obrazovky:

![f](https://user-images.githubusercontent.com/1244233/78773000-e1e09780-7992-11ea-9742-b717fd0230c6.png)

vs.

![f (1)](https://user-images.githubusercontent.com/1244233/78773006-e311c480-7992-11ea-995f-88e31c79dbd2.png)

**Comment by filiplikavcan** [comment]
OK, po diskusii s Lukasom to uzatvarame tak, ze to budu dve obrazovky.
