### ISSUE TITLE
Na niektorych strankach chyba posledny infobox s telefonnym cislom pre dalsie informacie. Je to ok?

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#61]
<img width="594" alt="Screenshot 2020-04-09 at 12 22 57" src="https://user-images.githubusercontent.com/1244233/78885443-ebcecd00-7a5c-11ea-8193-0e43cb7c062b.png">

**Comment by frkosk** [comment]
áno, je to tak OK
