### ISSUE TITLE
nefunkčný back button

### ISSUE THREAD

**Issue by frkosk** [slovensko-help/korona-gov#63]
https://korona.slovensko.help/prva-a-druha-pomoc/dokumenty-pre-ziskanie-prispevku-szco-bez-zamestnancov/

**Comment by frkosk** [comment]
@filiplikavcan ustriehneš to, keď už sa hráš s back buttonm?

**Comment by filiplikavcan** [comment]
Hej, skontroloval som ich. Ked budeme mat final export do statiky, tak to este preklikame vsetko.
