### ISSUE TITLE
Zle otextovaný výkaz

### ISSUE THREAD

**Issue by Sekacka** [slovensko-help/korona-gov#64]
tu sa píše o výkaze, ale tlačidlá aj text sú o žiadosti

![image](https://user-images.githubusercontent.com/63402930/78891139-381f0a80-7a67-11ea-8f3c-6b121fa5e455.png)

tak aj sem link
https://korona.slovensko.help/prva-a-druha-pomoc/zamestnavatel-podklady-pre-ziskanie-prispevku/

**Comment by frkosk** [comment]
davaj sme aj link @Sekacka

**Comment by Sekacka** [comment]
https://korona.slovensko.help/prva-a-druha-pomoc/zamestnavatel-podklady-pre-ziskanie-prispevku/

**Comment by frkosk** [comment]
opravené
