### ISSUE TITLE
nejde tlačidlo Späť

### ISSUE THREAD

**Issue by Sekacka** [slovensko-help/korona-gov#65]
z tejtoo stránky nejde tlačidllo späť, hodí chybu 404

https://korona.slovensko.help/prva-a-druha-pomoc/zamestnavatel-podklady-pre-ziskanie-prispevku/

![image](https://user-images.githubusercontent.com/63402930/78891352-b4195280-7a67-11ea-88ac-66cb8f993b8f.png)

**Comment by frkosk** [comment]
Dík toto je duplicitné s issue #63
