### ISSUE TITLE
Cookie consent nespravne funguje v statickom exporte

### ISSUE THREAD

**Issue by backy-wellit** [slovensko-help/korona-gov#73]
https://korona.slovensko.help/prva-a-druha-pomoc/
Neuloží sa správne odkliknutie cookie banneru.

**Comment by Hucoo** [comment]
Nie je to bug. Je to nastavené na doménu https://wpkorona.lamer.sk/ ak to treba dať na inú, treba napísať - nikde som takú informáciu nemal.

**Comment by filiplikavcan** [comment]
Domeny budu: opatrenia.korona.gov.sk a www.opatrenia.korona.gov.sk

**Comment by backy-wellit** [comment]
@Hucoo nie je mozne to urobit tak, aby to dokazalo fungovat na roznych domenach sucasne?
