### ISSUE TITLE
Default sirka textu

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#83]
Na gov.uk aj na navody.digital pouzivame `two-thirds` wrapper. Odporucaju aj tu https://design-system.service.gov.uk/styles/layout/

Toto je prisiroke. 
![image](https://user-images.githubusercontent.com/26342/78925824-56532d80-7a9c-11ea-839c-1ef23f1a830d.png)

**Comment by frkosk** [comment]
Inde používame. Toto je dočasná stránka, čoskoro na nahradí...

**Comment by jsuchal** [comment]
Vsimol som si to aj inde, napriklad tu nie je two-thirds pouzite a "preteka" nadpis.
https://korona.slovensko.help/prva-a-druha-pomoc/dokumenty-pre-ziskanie-prispevku-szco-bez-zamestnancov/

**Comment by filiplikavcan** [comment]
Nadpisy su naschval na full a nie two thirds, lebo sa zbytocne lamali na vela riadkov a vyzeralo to cudne.

**Comment by jsuchal** [comment]
@filiplikavcan no ved mozno aj preto su tie nadpisy take velke, aby neboli prilis dlhe. Ak vsak spravne pozeram, tak GDS pouziva `l` a nie `xl` ako my. https://design-system.service.gov.uk/patterns/question-pages/

**Comment by frkosk** [comment]
XL je u nás H1. niektoré stránky majú hlbšiu štruktúru a potom sa H3 už strácali.

**Comment by jsuchal** [comment]
@frkosk co ja viem, co som to pozeral tak v klude skocite z xl rovno na m. Navyse https://design-system.service.gov.uk/styles/typography/#headings tu su tiez 4 velkosti headings.
