### ISSUE TITLE
Typography nazi

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#85]
https://abelovska.blog.sme.sk/c/320905/nenechavajte-ubohe-pismenka-a-cisla-osamotene-na-koncoch-riadkov.html

Specialne v nadpisoch to mi to specialne drazdi oci. A na mobile je to akurat tak zarovnane casto. Neviem ci na toto neni nejaky wordpress plugin.

![image](https://user-images.githubusercontent.com/26342/78926154-e4c7af00-7a9c-11ea-94a2-6dd324680fd1.png)

**Comment by Peter74** [comment]
Doplnil som nezalomiteľnú medzeru.
Toto je celkom tricky vyriešiť automaticky. Jednoduché riešenie, a teda bolo by asi dobré to potom vysvetliť aj redakcii, aby v názve stránky, kde je možnosť, že nejaké "úbohé písmenko", alebo "čísielko" :) ostane osamotené na konci riadku, aby medzi neho a nasledujúce slovo, vložili namiesto obyčajnej medzery `&nbsp;` <- toto je napríklad vhodné používať aj pri sumách 90 €`90&nbsp;€` hlavne v texte, kde by mohlo dôjsť k nežiadúcemu zalomeniu, práve medzi číslom a znakom meny.

**Comment by RUjmiak** [comment]
@Peter74 posielam kuzelny skript. Je potrebne upravit elementy, ktorych sa to ma tykat.

`
$('h1, h2, h3, p').each(function() {
        var html = $.trim($(this).html());
        $(this).html(html.replace(/([^\s])\s+([^\s])(\s+|$)/g, "$1 $2&nbsp;"));
});
`
