### ISSUE TITLE
Podstranka prva a druha pomoc

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#86]
Ten druhy nadpis je prilis velky zmenit z `xl` na `l`. 

![image](https://user-images.githubusercontent.com/26342/78926563-91099580-7a9d-11ea-8dd8-775bacd24d03.png)

Taktiez toto je zvlastny flow

![image](https://user-images.githubusercontent.com/26342/78926788-fc536780-7a9d-11ea-97c0-6c1f27ccd3dc.png)

Je tam button (call-to-action) a nasledne este kopec dalsich linkov. Ak to su alternativy, tak by asi mal zmysel skor https://design-system.service.gov.uk/components/accordion/

Ak budu za tym "viac informacii" linky na ziadosti, tak toto neni vhodny pattern. Mozno aj klasicke "dlazdice" s textom by mali zmysel.

Tie taby su divne, asi by som skor preferoval rozcestnik pre rozne kategoria (tak ako to je vlastne na mobile) a naprikald aj tu https://www.nhs.uk/conditions/coronavirus-covid-19/

Na mobile je to vsetko na jednej stranke, to uplne nedava zmysel. Ja by som to rozdelil na dve.

**Comment by frkosk** [comment]
> Ten druhy nadpis je prilis velky zmenit z xl na l.

Druhý nadpis potrebjeme mať väčší, lebo na mobile to sa tá sekcia zlieva.

> Je tam button (call-to-action) a nasledne este kopec dalsich linkov. Ak to su alternativy, tak by asi mal zmysel skor https://design-system.service.gov.uk/components/accordion/

Máme toto jedno opatrenie a potrebujeme naň upozorniť.

> Ak budu za tym "viac informacii" linky na ziadosti, tak toto neni vhodny pattern. Mozno aj klasicke "dlazdice" s textom by mali zmysel.

Keď bude viac opatrení bude iné riešenie. Teraz bolo dôležité tam pridať aspoň nejaké info k ostatným opatreniam.

> Tie taby su divne, asi by som skor preferoval rozcestnik pre rozne kategoria (tak ako to je vlastne na mobile) a naprikald aj tu https://www.nhs.uk/conditions/coronavirus-covid-19/
Na mobile je to vsetko na jednej stranke, to uplne nedava zmysel. Ja by som to rozdelil na dve.

Priznajme si, taby nikdy neboli ideálne riešenie.

Môj konečný verdikt teda je, že zatiaľ fajn. Keď to bude dávať zmysel, bude aj lepšie riešenie
