### ISSUE TITLE
Ziadost o podporu

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#87]
![image](https://user-images.githubusercontent.com/26342/78927872-e21a8900-7a9f-11ea-9570-d86bc7df3aba.png)

Toto je duplicitny text. Opat by to chcelo vystizny leading paragraph. 

![image](https://user-images.githubusercontent.com/26342/78927918-f78fb300-7a9f-11ea-9623-5cf95214e1a8.png)

Tu otazku treba dat tesne pred tie buttony. 

Je zlastne, ze jeden je zeleny a druhy sivy. Evokuje to vo mne, ze narok maju len ti co maju zamestnancov. 

Ozajstny pattern na toto je option, ale chapem limitacie statiky.

**Comment by frkosk** [comment]
Hej, option by bol fajn... uvidíme ako zrozumiteľné to je pri testovaní.
