### ISSUE TITLE
Boli ste nútení zatvoriť alebo obmedziť svoju činnosť z rozhodnutia Úradu verejného zdravotníctva SR?

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#89]
![image](https://user-images.githubusercontent.com/26342/78928383-cc599380-7aa0-11ea-8eed-e93a31d1c082.png)

Toto preteka cez two-thirds. 

![image](https://user-images.githubusercontent.com/26342/78928428-e004fa00-7aa0-11ea-9b94-a7fcfb135ed2.png)

To podciarknutie je divne.

Tie texty na buttonoch s lomitkami kvoli sklonovaniu su nic moc.

**Comment by ljurena** [comment]
Podčiarknutie môžeme potom. Zmeniť.   
Popis v buttonich sme menili, pretože najprv bol v mužskom rode, takto je to rodovo neutrálne :). Plural bol síce neutrálny, no znelo to divne.

**Comment by filiplikavcan** [comment]
Mne sa tato forma “nútený/á” tiez moc nepozdava.

**Comment by athelas64** [comment]
Podčiarknutie textu, ktorý nie je odkaz, je porušením prístupnosti. Okrem toho, je tam úplne zbytočné, nie je potrebné ani hľadať inú formu zvýraznenia.

**Comment by frkosk** [comment]
Podčiarknutia sú preč, texty v buttonoch zatiaľ necháme tak.
