### ISSUE TITLE
Warning text ma byt cely boldom?

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-help/korona-gov#9]
V idsk je cely boldom: https://idsk-preview.herokuapp.com/components/inset-text
Vo figme ma normalny rez a niektore slova su zvyraznene boldom.

**Comment by frkosk** [comment]
Navrhujem upraviť si v takom prípade html. Namiesto tagu `<strong>` použiť `<span>` a následne text formátovať podla potreby.

`<div class="govuk-warning-text">
  <span class="govuk-warning-text__icon" aria-hidden="true">!</span>
  <span class="govuk-warning-text__text">
    <span class="govuk-warning-text__assistive">Warning</span>
    You can be fined up to £5,000 if you don’t register.
  </span>
</div>`

**Comment by filiplikavcan** [comment]
Dakujem.
