### ISSUE TITLE
Potrebné dokumenty pre získanie príspevku 80 % mzdy

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#90]
![image](https://user-images.githubusercontent.com/26342/78929181-34f54000-7aa2-11ea-9a1d-cbfa83514812.png)

Tu je ten button bez sipky. (Inak oficialne v dizajn manuali sa sipka pouziva len ked startujes nejaku sluzbu

**Comment by frkosk** [comment]
upratal som šípky
