### ISSUE TITLE
Žiadosť o príspevok

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#91]
![image](https://user-images.githubusercontent.com/26342/78929287-63731b00-7aa2-11ea-872d-3a2094c5e025.png)

Toto treba urcite rozdelit na viac stranok. Prva by mala koncit tym, ze to odoslem na adresu a potom stlacim "Ano, prilozil som prilohy, nastavil subjekt a odoslal som to".

Pomocka by by mohla byt, ze viem kliknut na emailovu adresu a cez mailto: sa to otvori so spravnym senderom, obsahom emailu.

Nasledne by bola dalsia stranka, kde by bolo napisane "Co sa bude diat dalej?" a zvysok tejto stranky.

Takto je to matuce lebo clvoek nespravi tu akciu a cita dalej.

**Comment by ljurena** [comment]
Presne tak ako to navrhujes sme to bali v I. iterácii, ale zhodli sme sa na tom, že ak by sme to dali na dalsiu stránku, hrozilo by, že užívateľ odosle a moze odginoirovat alebo si nevsimne tie dalsie kroky. Kedže v ďalších krokoch je nevyhnutný podpis žiadateľa a opätovné zaslanie úradu bze ktorého mu nebude vyplatení pomoc, tak sme sa rozhodli to ponechať na jednej obrazovke. 

Čo sa týka "mailto:" to je myslím v backlogu.

**Comment by jsuchal** [comment]
Hej, ale tak je to trosku v rozpore so samotnym dizajn manualom. https://idsk-preview.herokuapp.com/vzory/stranky-dokoncenia-procesu

Ja predpokladam, ze tie dalsie kroky mu pridu aj potom, cize notifikacia na email s dalsimi pokynmi by bola nepriestrelnejsie riesenie.

**Comment by ljurena** [comment]
Určite bolo a súhlasím. Pochop prosím, ze sa nedajú vyriešiť dlhoročné resty za týždeň, s malým tímom a aktuálne dôležitejší prioritami. Komunikácia s ministerstvo žiaľ nie je ideálna a sme radi aj za toto MVP, čiže notifikácne maily sú zatial v backlogu. Náš focus je nateraz pridaná hodnota pre občana. Toto je prvá iteracia, verím ze bude čas a priestor na vylepšovanie, potom sa pokojne zapoj.

**Comment by filiplikavcan** [comment]
Ta cast procesu po odoslani emailu je mimo dosahu ludi, co robia tieto navody. Teraz si ale uvedomujem, ze ten format navody.digital by tu bol super.

**Comment by jsuchal** [comment]
@ljurena no takto, pokial pokyny naozaj neposielaju aj emailom, tak to je naslapna mina. Obcana naozaj nebude zaujimat ci zlyhalo UPVII alebo urad prace ci socialka.

**Comment by frkosk** [comment]
Toto zatiaľ uzatváram. Uvidíme čo vypadne z ministerstva a testovania s používateľmi
