### ISSUE TITLE
Nastavenie anonymizeIP kvoli GDPR

### ISSUE THREAD

**Issue by jsuchal** [slovensko-help/korona-gov#97]
Z pohladu GDPR je IP adresa osobny udaj, cize to treba vypnut. Ak pozeram spravne, tak neni nastavene anonymizeIp. https://www.optimizesmart.com/how-to-turn-on-ip-anonymization-in-google-analytics-and-google-tag-manager/

**Comment by Hucoo** [comment]
Toto je nastavené.

**Comment by jsuchal** [comment]
@Hucoo ano teraz to tam vidim, neviem ci som to predtym nevidel alebo sa po ceste nieco zmenilo.

**Comment by Hucoo** [comment]
@jsuchal nene, nebolo to tam, ja som to upravil po vytvorení tohto tásku.

**Comment by jsuchal** [comment]
Dobre dobre. Už som mal pocit, že sa mi snívalo.
