### ISSUE TITLE
grammar/typo nazi %

### ISSUE THREAD

**Issue by athelas64** [slovensko-help/korona-gov#98]
Na stránke https://wpkorona.lamer.sk/prva-a-druha-pomoc/ sa percentá píšu tak voľne, raz spolu s číslom, inokedy oddelené. Podľa [JÚĽS ](https://jazykovaporadna.sme.sk/q/1312/)sa percentá vždy píšu oddelené medzerou, mi posadnutí typografiou sa len hádame o tom, akou širokou. Asi by bolo dobré v rámci celého sídla v html dokumentoch:
- pred všetky značky percentá vložiť &nbsp;
- ak sa pred percentami už nachádza medzera, túto nahradiť &nbsp;

Ak by ste to chceli pekné, tak &thinsp; - lenže tú prehliadač rozdeľuje
Sú hacky na to, ako spraviť, aby nerozdeliteľná medzera bola tenšia, ale neviem, či je to stojí za úsilie a znásilňovanie unicode ([`&#8239;`](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation)).

**Comment by Peter74** [comment]
Všade v obsahu som podopĺňal `&nbsp;`
