### ISSUE TITLE
vyhlásenie o prístupnosti 

### ISSUE THREAD

**Issue by athelas64** [slovensko-help/korona-gov#99]
Vypracovať na zverejniť s linkom z homepage **Vyhlásenie o prístupnosti**
Template a viac informácií: [Povinné vyhlásenie o prístupnosti](https://www.vicepremier.gov.sk/sekcie/informatizacia/governance-a-standardy/standardy-isvs/pristupnost-webovych-sidel/povinne-vyhlasenie-o-pristupnosti-weboveho-sidla-mobilnej-aplikacie/index.html)

(Povinnosť vyplýva z nariadení Európskej komisie)

**Comment by b0n0r** [comment]
duplicate of #7
